name: Generate Space Shooter

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-game:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: czl9707/gh-space-shooter@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: "game.gif"
          strategy: "random"
